In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from scipy.stats import f_oneway
import warnings
warnings.filterwarnings('ignore')

<h1>Road Accident Data Analysis</h1>
<h3>Analyst: Ian Genesis Minorca</h3>

In [2]:
acci = pd.read_csv('datasets\\accident_data.csv')
acci

,Index,Accident_Severity,Accident Date,Latitude,Light_Conditions,District Area,Longitude,Number_of_Casualties,Number_of_Vehicles,Road_Surface_Conditions,Road_Type,Urban_or_Rural_Area,Weather_Conditions,Vehicle_Type
0,200701BS64157,Serious,05/06/2019,51.506187,Darkness - lights lit,Kensington and Chelsea,-0.209082,1,2,Dry,Single carriageway,Urban,Fine no high winds,Car
1,200701BS65737,Serious,02/07/2019,51.495029,Daylight,Kensington and Chelsea,-0.173647,1,2,Wet or damp,Single carriageway,Urban,Raining no high winds,Car
2,200701BS66127,Serious,26/08/2019,51.517715,Darkness - lighting unknown,Kensington and Chelsea,-0.210215,1,3,Dry,NaN,Urban,NaN,Taxi/Private hire car
3,200701BS66128,Serious,16/08/2019,51.495478,Daylight,Kensington and Chelsea,-0.202731,1,4,Dry,Single carriageway,Urban,Fine no high winds,Bus or coach (17 or more pass seats)
4,200701BS66837,Slight,03/09/2019,51.488576,Darkness - lights lit,Kensington and Chelsea,-0.192487,1,2,Dry,NaN,Urban,NaN,Other vehicle
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
660674,201091NM01760,Slight,18/02/2022,57.374005,Daylight,Highland,-3.467828,2,1,Dry,Single carriageway,Rural,Fine no high winds,Car
660675,201091NM01881,Slight,21/02/2022,57.232273,Darkness - no lighting,Highland,-3.809281,1,1,Frost or ice,Single carriageway,Rural,Fine no high winds,Car
660676,201091NM01935,Slight,23/02/2022,57.585044,Daylight,Highland,-3.862727,1,3,Frost or ice,Single carriageway,Rural,Fine no high winds,Car
660677,201091NM01964,Serious,23/02/2022,57.214898,Darkness - no lighting,Highland,-3.823997,1,2,Wet or damp,Single carriageway,Rural,Fine no high winds,Motorcycle over 500cc
660678,201091NM02142,Serious,28/02/2022,57.575210,Daylight,Highland,-3.895673,1,1,Wet or damp,Dual carriageway,Rural,Snowing no high winds,Car

In [3]:
acci['Accident Date'] = pd.to_datetime(acci['Accident Date'], errors = "coerce")
acci.dtypes

Index                              object
Accident_Severity                  object
Accident Date              datetime64[ns]
Latitude                          float64
Light_Conditions                   object
District Area                      object
Longitude                         float64
Number_of_Casualties                int64
Number_of_Vehicles                  int64
Road_Surface_Conditions            object
Road_Type                          object
Urban_or_Rural_Area                object
Weather_Conditions                 object
Vehicle_Type                       object
dtype: object

In [4]:
acci['Accident Date']

0        2019-05-06
1        2019-02-07
2               NaT
3               NaT
4        2019-03-09
            ...
660674          NaT
660675          NaT
660676          NaT
660677          NaT
660678          NaT
Name: Accident Date, Length: 660679, dtype: datetime64[ns]

In [5]:
df_categor = acci.dropna(subset=["Accident_Severity", "Number_of_Casualties", "Number_of_Vehicles"])
df_categor

,Index,Accident_Severity,Accident Date,Latitude,Light_Conditions,District Area,Longitude,Number_of_Casualties,Number_of_Vehicles,Road_Surface_Conditions,Road_Type,Urban_or_Rural_Area,Weather_Conditions,Vehicle_Type
0,200701BS64157,Serious,2019-05-06,51.506187,Darkness - lights lit,Kensington and Chelsea,-0.209082,1,2,Dry,Single carriageway,Urban,Fine no high winds,Car
1,200701BS65737,Serious,2019-02-07,51.495029,Daylight,Kensington and Chelsea,-0.173647,1,2,Wet or damp,Single carriageway,Urban,Raining no high winds,Car
2,200701BS66127,Serious,NaT,51.517715,Darkness - lighting unknown,Kensington and Chelsea,-0.210215,1,3,Dry,NaN,Urban,NaN,Taxi/Private hire car
3,200701BS66128,Serious,NaT,51.495478,Daylight,Kensington and Chelsea,-0.202731,1,4,Dry,Single carriageway,Urban,Fine no high winds,Bus or coach (17 or more pass seats)
4,200701BS66837,Slight,2019-03-09,51.488576,Darkness - lights lit,Kensington and Chelsea,-0.192487,1,2,Dry,NaN,Urban,NaN,Other vehicle
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
660674,201091NM01760,Slight,NaT,57.374005,Daylight,Highland,-3.467828,2,1,Dry,Single carriageway,Rural,Fine no high winds,Car
660675,201091NM01881,Slight,NaT,57.232273,Darkness - no lighting,Highland,-3.809281,1,1,Frost or ice,Single carriageway,Rural,Fine no high winds,Car
660676,201091NM01935,Slight,NaT,57.585044,Daylight,Highland,-3.862727,1,3,Frost or ice,Single carriageway,Rural,Fine no high winds,Car
660677,201091NM01964,Serious,NaT,57.214898,Darkness - no lighting,Highland,-3.823997,1,2,Wet or damp,Single carriageway,Rural,Fine no high winds,Motorcycle over 500cc
660678,201091NM02142,Serious,NaT,57.575210,Daylight,Highland,-3.895673,1,1,Wet or damp,Dual carriageway,Rural,Snowing no high winds,Car

<h1>Data Cleansing</h1>

In [6]:
acci['Latitude'] =  acci['Latitude'].fillna(acci['Latitude'].mode()[0])
acci['Longitude'] =  acci['Longitude'].fillna(acci['Longitude'].mode()[0])
acci['Road_Surface_Conditions'] =  acci['Road_Surface_Conditions'].fillna('Unknown Surface Conditiion')
acci['Road_Type'] =  acci['Road_Type'].fillna('Unaccounted')
acci['Weather_Conditions'] =  acci['Weather_Conditions'].fillna('Unaccounted')
acci['Urban_or_Rural_Area'] =  acci['Urban_or_Rural_Area'].fillna(acci['Urban_or_Rural_Area'].mode()[0])

In [7]:
acci['Accident_Severity'] = acci['Accident_Severity'].astype('category')
acci['Latitude'] = acci['Latitude'].astype('category')
acci['Light_Conditions'] = acci['Light_Conditions'].astype('category')
acci['District Area'] = acci['District Area'].astype('category')
acci['Longitude'] = acci['Longitude'].astype('category')
acci['Road_Surface_Conditions'] = acci['Road_Surface_Conditions'].astype('category')
acci['Road_Type'] = acci['Road_Type'].astype('category')
acci['Urban_or_Rural_Area'] = acci['Urban_or_Rural_Area'].astype('category')
acci['Weather_Conditions'] = acci['Weather_Conditions'].astype('category')
acci['Vehicle_Type'] = acci['Vehicle_Type'].astype('category')

In [8]:
acci.dtypes

Index                              object
Accident_Severity                category
Accident Date              datetime64[ns]
Latitude                         category
Light_Conditions                 category
District Area                    category
Longitude                        category
Number_of_Casualties                int64
Number_of_Vehicles                  int64
Road_Surface_Conditions          category
Road_Type                        category
Urban_or_Rural_Area              category
Weather_Conditions               category
Vehicle_Type                     category
dtype: object

<h1>Extracting Date Info with Pandas date/time</h1>

In [9]:
acci['Year'] = acci['Accident Date'].dt.year
acci['Month'] = acci['Accident Date'].dt.month
acci['Day'] = acci['Accident Date'].dt.day
acci['DayOfweek'] = acci['Accident Date'].dt.dayofweek
acci.isnull().sum()

Index                           0
Accident_Severity               0
Accident Date              395672
Latitude                        0
Light_Conditions                0
District Area                   0
Longitude                       0
Number_of_Casualties            0
Number_of_Vehicles              0
Road_Surface_Conditions         0
Road_Type                       0
Urban_or_Rural_Area             0
Weather_Conditions              0
Vehicle_Type                    0
Year                       395672
Month                      395672
Day                        395672
DayOfweek                  395672
dtype: int64

<h1 style="color:yellow;">Insight 1</h1>
<h3>Severity</h3>

In [10]:
acci[acci['Accident_Severity'] == 'Serious']['District Area'].mode()[0]

'Birmingham'

<h1 style="color:yellow;">Insight 2</h1>
<h3>Distribution of accident severity</h3>

In [45]:
# severity_counts = acci["Accident_Severity"].value_counts().T
# severity_counts
sev = acci.groupby(['Accident_Severity', 'District Area'])['Number_of_Casualties'].count().unstack().T.head(20)
sev

Accident_Severity      Fatal  Serious  Slight
District Area
Aberdeen City             12      239    1072
Aberdeenshire             66      463    1401
Adur                       8      101     510
Allerdale                 24      143     961
Alnwick                    6       33     193
Amber Valley              19      173    1155
Angus                     32      163     601
Argyll and Bute           27      184     625
Arun                      15      253    1108
Ashfield                  11      201    1183
Ashford                   26      167    1512
Aylesbury Vale            28      257    1552
Babergh                   20      157     872
Barking and Dagenham      20      172    1577
Barnet                    46      474    3830
Barnsley                  35      304    2189
Barrow-in-Furness          6       65     572
Basildon                  16      221    1456
Basingstoke and Deane     34      197    1236
Bassetlaw                 38      256    1242

<h1 style="color:yellow;">Insight 3</h1>
<h3>Most common road type where accidents occur</h3>

In [12]:
most_common_road = acci["Road_Type"].mode()[0]
most_common_road

'Single carriageway'

<h1 style="color:yellow;">Insight 4</h1>
<h3>Number of accidents per district (top 5)</h3>

In [13]:
top_districts = acci["District Area"].value_counts().head(5)
top_districts

District Area
Birmingham    13491
Leeds          8898
Manchester     6720
Bradford       6212
Sheffield      5710
Name: count, dtype: int64

<h1 style="color:yellow;">Insight 5</h1>
<h3>Most common vehicle type involved in accidents</h3>

In [14]:
common_vehicle = acci["Vehicle_Type"].mode()[0]
common_vehicle

'Car'

<h1 style="color:yellow;">Insight 6</h1>
<h3>Number of accidents over the years</h3>

In [15]:
yr_acci = acci["Accident Date"].dt.year.value_counts().sort_index()
yr_acci

Accident Date
2019.0    71867
2020.0    70163
2021.0    66172
2022.0    56805
Name: count, dtype: int64

<h1 style="color:yellow;">Insight 7</h1>
<h3>Day of the week with the most accidents</h3>

In [16]:
mostday = acci["Accident Date"].dt.day_name().mode()[0]
mostday

'Tuesday'

<h1 style="color:yellow;">Insight 8</h1>
<h3>Maximum casualties recorded in a single accident</h3>

In [17]:
max_casualties = acci["Number_of_Casualties"].max()
max_casualties

68

<h1 style="color:yellow;">Insight 9</h1>
<h3>Correlation between number of vehicles and casualties</h3>

In [18]:
corre = acci[["Number_of_Casualties", "Number_of_Vehicles"]].corr().iloc[0, 1]
corre>0.05

True

<h1 style="color:yellow;">Insight 10</h1>
<h3>Proportion of urban vs rural accidents</h3>

In [19]:
ur_ru = acci["Urban_or_Rural_Area"].value_counts(normalize=True) * 100
ur_ru

Urban_or_Rural_Area
Urban          63.824944
Rural          36.173391
Unallocated     0.001665
Name: proportion, dtype: float64

<h1 style="color:yellow;">Insight 11</h1>
<h3>Most common weather condition</h3>

In [20]:
common_weather = acci["Weather_Conditions"].T.mode()[0]
common_weather

'Fine no high winds'

<h1 style="color:yellow;">Insight 12</h1>
<h3>Average number of casualties per accident</h3>

In [21]:
avg_cas = acci["Number_of_Casualties"].mean()
avg_cas

1.357040257068864

<h1 style="color:yellow;">Insight 13</h1>
<h3>Accidents in 2020</h3>

In [22]:
acci_19 = acci[acci['Year'] == 2020].head(15)
acci_19

,Index,Accident_Severity,Accident Date,Latitude,Light_Conditions,District Area,Longitude,Number_of_Casualties,Number_of_Vehicles,Road_Surface_Conditions,Road_Type,Urban_or_Rural_Area,Weather_Conditions,Vehicle_Type,Year,Month,Day,DayOfweek
182120,200801BS70001,Serious,2020-02-01,51.491521,Darkness - lights lit,Kensington and Chelsea,-0.179406,1,2,Dry,Single carriageway,Urban,Fine no high winds,Car,2020.0,2.0,1.0,5.0
182121,200801BS70002,Slight,2020-06-01,51.484909,Darkness - lights lit,Kensington and Chelsea,-0.176356,1,2,Wet or damp,Single carriageway,Urban,Fine no high winds,Motorcycle over 500cc,2020.0,6.0,1.0,0.0
182122,200801BS70003,Serious,2020-12-01,51.509965,Daylight,Kensington and Chelsea,-0.197405,1,1,Dry,Single carriageway,Urban,Fine no high winds,Car,2020.0,12.0,1.0,1.0
182123,200801BS70004,Slight,2020-05-01,51.490631,Darkness - lights lit,Kensington and Chelsea,-0.185779,1,2,Dry,Single carriageway,Urban,Fine no high winds,Car,2020.0,5.0,1.0,4.0
182124,200801BS70005,Slight,2020-03-01,51.509712,Darkness - lights lit,Kensington and Chelsea,-0.192659,3,1,Dry,Single carriageway,Urban,Fine no high winds,Car,2020.0,3.0,1.0,6.0
182125,200801BS70006,Serious,2020-07-01,51.494069,Daylight,Kensington and Chelsea,-0.158271,1,2,Dry,Single carriageway,Urban,Fine no high winds,Goods over 3.5t. and under 7.5t,2020.0,7.0,1.0,2.0
182126,200801BS70007,Slight,2020-04-01,51.482141,Darkness - lights lit,Kensington and Chelsea,-0.183380,1,2,Wet or damp,Single carriageway,Urban,Raining no high winds,Motorcycle over 500cc,2020.0,4.0,1.0,2.0
182127,200801BS70008,Slight,2020-04-01,51.515424,Darkness - lights lit,Kensington and Chelsea,-0.213332,2,2,Wet or damp,Single carriageway,Urban,Raining no high winds,Goods 7.5 tonnes mgw and over,2020.0,4.0,1.0,2.0
182128,200801BS70009,Slight,2020-07-01,51.478418,Daylight,Kensington and Chelsea,-0.181080,1,3,Dry,Single carriageway,Urban,Fine no high winds,Car,2020.0,7.0,1.0,2.0
182129,200801BS70010,Slight,2020-07-01,51.488522,Darkness - lights lit,Kensington and Chelsea,-0.165841,1,2,Dry,Single carriageway,Urban,Fine no high winds,Car,2020.0,7.0,1.0,2.0
182131,200801BS70012,Slight,2020-01-01,51.501340,Darkness - lights lit,Westminster,-0.180455,1,2,Dry,Single carriageway,Urban,Fine no high winds,Car,2020.0,1.0,1.0,2.0
182134,200801BS70015,Slight,2020-04-01,51.494902,Darkness - lights lit,Kensington and Chelsea,-0.182872,1,1,Wet or damp,Single carriageway,Urban,Raining no high winds,Car,2020.0,4.0,1.0,2.0
182135,200801BS70016,Slight,2020-12-01,51.523431,Daylight,Kensington and Chelsea,-0.213595,1,1,Dry,Single carriageway,Urban,Fine no high winds,Goods 7.5 tonnes mgw and over,2020.0,12.0,1.0,1.0
182136,200801BS70017,Slight,2020-12-01,51.495117,Darkness - lights lit,Kensington and Chelsea,-0.173500,3,3,Wet or damp,Dual carriageway,Urban,Raining no high winds,Goods 7.5 tonnes mgw and over,2020.0,12.0,1.0,1.0
182137,200801BS70018,Slight,2020-10-01,51.483165,Daylight,Kensington and Chelsea,-0.185644,1,2,Wet or damp,Single carriageway,Urban,Raining no high winds,Car,2020.0,10.0,1.0,3.0

<h1 style="color:yellow;">Insight 14</h1>
<h3>20 Accident Peak Dates</h3>

In [23]:
hr = print(f"These are the peak {acci['Accident Date'].value_counts().head(20)}")
hr

These are the peak Accident Date
2021-11-02    685
2021-06-10    680
2019-06-12    678
2019-01-02    676
2021-04-12    667
2021-12-11    659
2019-05-10    657
2022-01-10    656
2019-12-12    655
2019-11-12    653
2019-02-02    652
2020-05-09    648
2021-03-11    646
2019-03-12    645
2020-11-01    644
2019-09-10    634
2020-05-12    633
2022-01-02    631
2021-11-12    630
2019-02-05    629
Name: count, dtype: int64

<h1 style="color:yellow;">Insight 15</h1>
<h3>What road type is the most prone to accident?</h3>

In [34]:
acci_road = acci['Road_Type'].value_counts()
acci_road

Road_Type
Single carriageway    492143
Dual carriageway       99424
Roundabout             43992
One way street         13559
Slip road               7041
Unaccounted             4520
Name: count, dtype: int64

<h1 style="color:yellow;">Insight 16</h1>
<h3>Accident in Dry Roads</h3>

In [25]:
i = acci[acci['Road_Surface_Conditions'] == "Dry"]
i

,Index,Accident_Severity,Accident Date,Latitude,Light_Conditions,District Area,Longitude,Number_of_Casualties,Number_of_Vehicles,Road_Surface_Conditions,Road_Type,Urban_or_Rural_Area,Weather_Conditions,Vehicle_Type,Year,Month,Day,DayOfweek
0,200701BS64157,Serious,2019-05-06,51.506187,Darkness - lights lit,Kensington and Chelsea,-0.209082,1,2,Dry,Single carriageway,Urban,Fine no high winds,Car,2019.0,5.0,6.0,0.0
2,200701BS66127,Serious,NaT,51.517715,Darkness - lighting unknown,Kensington and Chelsea,-0.210215,1,3,Dry,Unaccounted,Urban,Unaccounted,Taxi/Private hire car,NaN,NaN,NaN,NaN
3,200701BS66128,Serious,NaT,51.495478,Daylight,Kensington and Chelsea,-0.202731,1,4,Dry,Single carriageway,Urban,Fine no high winds,Bus or coach (17 or more pass seats),NaN,NaN,NaN,NaN
4,200701BS66837,Slight,2019-03-09,51.488576,Darkness - lights lit,Kensington and Chelsea,-0.192487,1,2,Dry,Unaccounted,Urban,Unaccounted,Other vehicle,2019.0,3.0,9.0,5.0
5,200701BS67159,Serious,NaT,51.497750,Daylight,Kensington and Chelsea,-0.192556,2,3,Dry,Single carriageway,Urban,Fine no high winds,Car,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
660648,201091NL06327,Slight,2022-12-11,60.157151,Daylight,Shetland Islands,-1.146277,1,1,Dry,Single carriageway,Rural,Fine no high winds,Motorcycle over 500cc,2022.0,12.0,11.0,6.0
660649,201091NL06425,Slight,NaT,60.189955,Darkness - no lighting,Shetland Islands,-1.224047,1,2,Dry,Single carriageway,Rural,Unaccounted,Car,NaN,NaN,NaN,NaN
660651,201091NL06820,Slight,2022-04-12,60.154438,Darkness - lights lit,Shetland Islands,-1.143285,1,1,Dry,Single carriageway,Rural,Fine no high winds,Car,2022.0,4.0,12.0,1.0
660670,201091NM00939,Slight,NaT,57.574536,Darkness - lights lit,Highland,-3.892627,1,2,Dry,Single carriageway,Rural,Fine no high winds,Car,NaN,NaN,NaN,NaN
660674,201091NM01760,Slight,NaT,57.374005,Daylight,Highland,-3.467828,2,1,Dry,Single carriageway,Rural,Fine no high winds,Car,NaN,NaN,NaN,NaN

<h1 style="color:yellow;">Insight 17</h1>
<h3>The number of casualties in a certain vehicle and the weather conditions</h3>

In [51]:
e = acci.groupby(['Vehicle_Type', 'Weather_Conditions'])['Number_of_Casualties'].count().unstack()
e

Weather_Conditions,Fine + high winds,Fine no high winds,Fog or mist,Other,Raining + high winds,Raining no high winds,Snowing + high winds,Snowing no high winds,Unaccounted
Vehicle_Type,,,,,,,,,
Agricultural vehicle,20,1513,9,57,37,244,3,22,42
Bus or coach (17 or more pass seats),350,20398,134,609,389,3182,32,219,565
Car,6463,392668,2641,12993,7206,59940,677,4748,10656
Data missing or out of range,1,4,0,0,0,0,0,0,1
Goods 7.5 tonnes mgw and over,251,13589,93,459,275,2114,28,149,349
Goods over 3.5t. and under 7.5t,94,4823,31,151,83,729,6,52,127
Minibus (8 - 16 passenger seats),34,1552,14,50,27,245,2,16,36
Motorcycle 125cc and under,180,12064,82,388,220,1830,16,146,343
Motorcycle 50cc and under,106,6017,50,197,107,897,6,75,148
Motorcycle over 125cc and up to 500cc,87,6069,45,204,117,893,10,72,159
Motorcycle over 500cc,315,20245,118,655,354,3135,33,254,548
Other vehicle,57,4450,38,155,99,643,4,50,141
Pedal cycle,1,161,3,2,3,18,0,3,6
Ridden horse,0,3,0,0,0,1,0,0,0
Taxi/Private hire car,187,10452,78,328,190,1622,20,136,281
Van / Goods 3.5 tonnes mgw or under,408,26877,192,902,508,4203,48,296,726

<h1 style="color:yellow;">Insight 18</h1>
<h3>Top 5 road accidents</h3>

In [50]:
acci_roadz = acci['Road_Type'].value_counts().rank()
acci_roadz

Road_Type
Single carriageway    6.0
Dual carriageway      5.0
Roundabout            4.0
One way street        3.0
Slip road             2.0
Unaccounted           1.0
Name: count, dtype: float64

<h1 style="color:yellow;">Insight 19</h1>
<h3>Does Light Conditions affect the prone of accidents?</h3>

In [48]:
r = acci.groupby(['Number_of_Vehicles', 'Light_Conditions'])['Number_of_Casualties'].mean().unstack()
r

Light_Conditions,Darkness - lighting unknown,Darkness - lights lit,Darkness - lights unlit,Darkness - no lighting,Daylight
Number_of_Vehicles,,,,,
1,1.187967,1.192062,1.182015,1.373394,1.132589
2,1.326111,1.416834,1.348234,1.646493,1.353031
3,1.642674,1.687457,1.760417,1.941362,1.702329
4,1.584270,1.851108,2.153846,2.268226,2.009041
5,2.478261,2.115044,2.000000,2.629834,2.333890
6,1.400000,2.358108,2.000000,2.471429,2.716165
7,3.666667,2.672414,2.000000,3.257143,3.140704
8,2.250000,2.400000,NaN,4.068966,3.743243
9,NaN,2.733333,NaN,3.857143,3.514286
10,3.000000,2.666667,NaN,6.500000,3.222222
11,NaN,2.000000,NaN,2.000000,6.000000
12,NaN,1.000000,NaN,NaN,2.500000
13,NaN,8.500000,NaN,4.500000,10.500000
14,NaN,NaN,NaN,6.500000,4.600000
15,NaN,5.000000,NaN,NaN,NaN
16,NaN,8.500000,NaN,NaN,3.500000
19,NaN,13.000000,NaN,NaN,NaN
28,NaN,NaN,NaN,NaN,16.000000
32,NaN,NaN,NaN,NaN,5.000000

<h1 style="color:yellow;">Insight 20</h1>
<h3>Top Vehicle Types that was involved in accidents</h3>

In [29]:
corri = acci['Vehicle_Type'].value_counts().rank()
corri

Vehicle_Type
Car                                      16.0
Van / Goods 3.5 tonnes mgw or under      15.0
Bus or coach (17 or more pass seats)     14.0
Motorcycle over 500cc                    13.0
Goods 7.5 tonnes mgw and over            12.0
Motorcycle 125cc and under               11.0
Taxi/Private hire car                    10.0
Motorcycle over 125cc and up to 500cc     9.0
Motorcycle 50cc and under                 8.0
Goods over 3.5t. and under 7.5t           7.0
Other vehicle                             6.0
Minibus (8 - 16 passenger seats)          5.0
Agricultural vehicle                      4.0
Pedal cycle                               3.0
Data missing or out of range              2.0
Ridden horse                              1.0
Name: count, dtype: float64

In [30]:
acci.describe().T

,count,mean,min,25%,50%,75%,max,std
Accident Date,265007,2020-11-18 04:53:34.375468544,2019-01-01 00:00:00,2019-12-02 00:00:00,2020-11-05 00:00:00,2021-11-05 00:00:00,2022-12-12 00:00:00,NaN
Number_of_Casualties,660679.0,1.35704,1.0,1.0,1.0,1.0,68.0,0.824847
Number_of_Vehicles,660679.0,1.831255,1.0,1.0,2.0,2.0,32.0,0.715269
Year,265007.0,2020.407216,2019.0,2019.0,2020.0,2021.0,2022.0,1.101126
Month,265007.0,6.522028,1.0,4.0,7.0,10.0,12.0,3.467063
Day,265007.0,6.708374,1.0,4.0,7.0,10.0,12.0,3.445617
DayOfweek,265007.0,3.012203,0.0,1.0,3.0,5.0,6.0,1.987875